# Exercise Set 1 - Vectorizing Code

This notebook contains the exercises from the PDF. Fill in your answers in the code cells provided.

# Problem 1

We ask the students to use Python as the programming language for this course. This is the standard language used for Machine Learning

## Problem 1a

Visit the following links to warm up with NumPy exercises:
- https://www.w3resource.com/python-exercises/numpy/basic/index.php
- https://www.w3resource.com/python-exercises/numpy/index-array.php
- https://www.w3resource.com/python-exercises/numpy/linear-algebra/index.php
- https://www.w3resource.com/python-exercises/numpy/python-numpy-stat.php

This course assumes you have a fair knowledge of how numerical programming, (i.e. working with vectors and matrices programatically), works. In the following exercises, we will look at writing efficient, vectorised code. Assume that we have vectors:
- $\mathbf{a} \in \mathbb{R}^n$ with elements $\mathbf{a} = [a_1, \dots, a_n]^T$
- $\mathbf{b} \in \mathbb{R}^n$ with elements $\mathbf{b} = [b_1, \dots, b_n]^T$

Further assume we have a matrix $\mathbf{X} \in \mathbb{R}^{M \times N}$

$$
\mathbf{X} = \begin{bmatrix}
x_{11} & x_{12} & \dots & x_{1N} \\
\vdots & \vdots & \ddots & \vdots \\
x_{M1} & x_{M2} & \dots & x_{MN}
\end{bmatrix}
$$

The result vector is $\mathbf{y}$ which takes its dimensionality based on the problem.

In all problems, you should assume that the dimensions of the vectors and matrices involved are such that the matrix multiplications (and inner products) are valid. Note that e.g. $\mathbf{y} += k$ is the same as $\mathbf{y} = \mathbf{y} + k$.

## Problem 1b

Write the following sum as a mathematical vector operation:

$$ y = \sum_{i=1}^{n} a_i b_i $$

The sum of the dot product of two vectors (a and b) can be written in vectorform as $$ y = a^Tb $$

Where: 
- $a^T$ is the transpose of vector a 
- $b$ is the vector with elements $b_1,b_2,…,b_nb_1​,b_2​,…,b$
- $y$ is the scalar result of the dot product 


In [1]:
# Can use Numpy to solve this problem 
import numpy as np

# Assuming a and b are numpy arrays 
a = np.array([1, 2, 3])                # a = np.array([a1, a2, ...., an])
b = np.array([4, 5, 6])                # b = np.array([b1, b2, ...., bn])

# Calculate the dot product of a and b
dot_product = np.dot(a, b)             # can also use sum(a*b)
print(f'The dot product of a and b is: {dot_product}')

The dot product of a and b is: 32


## Problem 1c

Write this **for** loop as a mathematical vector operation and as vectorised code. 

```
for i=1,. . .,n:
    y+=a_i * b_i
```

Mathematical vector operation:

$$ y = \mathbf{a}^T \mathbf{b} $$

In [2]:
import numpy as np
n = 3

# Generate random arrays a and b of size n from 0 to 10
a = np.random.randint(0, 10, n)
b = np.random.randint(0, 10, n)

# The dot product of a and b 
y = np.dot(a, b)

print(f'The vector a is {a}')
print(f'The vector b is {b}')
print(f'The dot product of a and b is {y}')

The vector a is [1 1 5]
The vector b is [6 8 0]
The dot product of a and b is 14


## Problem 1d

Write this **for** loop as a mathematical vector operation and vectorised code (assume N = n)
```
for i=1,. . .,M:
    for k=1,. . .,n:
        y_i += x_{ik} * a_k
```

In [3]:
import numpy as np
m = 2       # num rows in matrix
n = 2       # size of vectors and num columns in matrix       

# Generate random arrays a and b of size n from 0 to 10
x = np.random.randint(0, 10, (m, n))
a = np.random.randint(0, 10, n)

# The vector matrix product of x and a 
y = np.dot(x, a)

print (f'The matrix x is \n{x}')
print (f'The vector a is {a}')
print (f'The matrix vector product of x and a is {y}')

The matrix x is 
[[8 1]
 [8 4]]
The vector a is [0 5]
The matrix vector product of x and a is [ 5 20]


## Problem 1e

Vectorise the following algorithm (answer with code). This shouldn’t be done with traditional matrix multiplications alone
```
for i=1,. . .,M:
    for k=1,. . .,n:
        y += x_{ik} * a_k
```

In [4]:
import numpy as np
m = 2       # num rows in matrix
n = 2       # size of vectors and num columns in matrix       

# Generate random arrays a and b of size n from 0 to 10
x = np.random.randint(0, 10, (m, n))
a = np.random.randint(0, 10, n)

# The vector matrix product of x and a 
y = np.sum(x * a)

print (f'The matrix x is \n{x}')
print (f'The vector a is {a}')
print (f'The matrix vector product of x and a is {y}')

The matrix x is 
[[8 4]
 [0 3]]
The vector a is [0 6]
The matrix vector product of x and a is 42


## Problem 1f

Let $\mathbf{Z} \in \mathbb{R}^{P \times M}$ and $z_{ij} \in \mathbf{Z}$ be the entry in row $i$ and column $j$.

Vectorize the following algorithm:

```
for j=1,. . .,N:
    for i=1,. . .,P:
        for k=1,. . .,M:
            y_{ij} += z_{ik} * x_{kj}
```

Hint: Consider how to express the sum as a matrix multiplication.

In [5]:
import numpy as np
m = 2       # num collums in Z and rows in X
p = 2       # num rows in Z and rows in the result of y 
n = 2       # num columns in X and columns in the result of Z

# Generate random arrays a and b of size n from 0 to 10
z = np.random.randint(0, 10, (p, m))
x = np.random.randint(0, 10, (m, n))

# The vector matrix product of x and a 
y = np.dot(z, x)

print (f'The matrix x is \n {x}')
print (f'The  matrix z is \n {z}')
print (f'The matrix vector product of x and a is \n {y}')

The matrix x is 
 [[3 7]
 [1 6]]
The  matrix z is 
 [[4 9]
 [5 9]]
The matrix vector product of x and a is 
 [[21 82]
 [24 89]]


## Problem 1g

**NB: This part problem has different notation!**

Suppose you have a dataset with \(N\) samples and \(n\) features:

$$
\mathbf{x}_1, \dots, \mathbf{x}_N, \mathbf{x}_i = [x_{i1}, \dots, x_{in}] \in \mathbb{R}^n
$$

Similarly, you have parameter vectors $\mathbf{w}_1, \dots, \mathbf{w}_P, \mathbf{w} $ in $\mathbb{R}^n$ and $(\mathbf{a} \in \mathbb{R}^P)$.

Implement an algorithm, for every single sample $(\mathbf{x}_j = [x_{j1}, \dots, x_{jn}])$ in the dataset, that calculates:

$$
v_i = \sum_{k=1}^{n} w_{ik} x_{jk}
$$

$$
y_j = \sum_{i=1}^{P} v_i a_i
$$

Vectorize these expressions. You want to end up with a vector $(\mathbf{y} \in \mathbb{R}^N)$.


### Answer

Have a dataset with N samples and n features. X is a N × n matrix where each row $w_j$ is a sample with n features. We also have

-  a parameter vector $w_1, ..., w_p$ where each $w_i" is a vector $R^n$ 
- a vector a in $R^P$

for each sample $x_j$ in the dataset, we compute 
$$ 
v_i = \sum^n_{k=1} w_{ik}x{jk} \\
y_j = \sum^P_{i=1} v_{i}a{i} 
$$

### Solution (the vectorized expression)
1. Compute V
    - V can be calculated as $XW^T$ where W is a $P×n$ matrix with $w_1,.....,w_P$ as rows 
    - This gives us a $N×P$ matrix V where each column i is represented by the result of $v_i$ for all samples 
2. Calculate y
    - y can be computed by multiplying V with vector a, in such a way that each row in C must be multiplied with a and the results are summed up and forms y. 

In [2]:
import numpy as np
N = 4       # num of samples 
n = 3       # num of features per sample 
P = 2       # num of parameter vectors


# Random choosen values for the data and parameters
X = np.random.rand(N, n)  # Datasett
W = np.random.rand(P, n)  # Parametervektorer
a = np.random.rand(P)     # Vektor a

# Compute matrix V as X times the transpose of W
V = np.dot(X, W.T)

# Compute vector y as the product of V and a
y = np.dot(V, a)

print(f'Dataset X is \n{X}')
print(f'Parameter vectors W is \n{W}')
print(f'The transpose of W is \n{W.T}')
print(f'Vector a is {a}')
print(f'Matrix V is \n{V}')
print(f'Vector y is {y}')


Dataset X is 
[[0.97463821 0.55974056 0.79176485]
 [0.12563745 0.02620869 0.55691325]
 [0.50616596 0.41727845 0.55131723]
 [0.27645441 0.88266256 0.5808705 ]]
Parameter vectors W is 
[[0.74617065 0.68310503 0.95462692]
 [0.49688177 0.65882913 0.62180522]]
The transpose of W is 
[[0.74617065 0.49688177]
 [0.68310503 0.65882913]
 [0.95462692 0.62180522]]
Vector a is [0.41817971 0.44911054]
Matrix V is 
[[1.86544806 1.34537686]
 [0.64329465 0.42598557]
 [1.18903346 0.86923176]
 [1.36374802 1.08007727]]
Vector y is [1.38431546 0.46032738 0.88761081 1.05536584]


## Problem 1h (Bonus)

Implement an algorithm that does matrix multiplication (without using built-in matrix multiplication functions).


In [11]:
import numpy as np

M, N, P = 3, 4, 2       # dimensions of the matrices (A and B)

# Random matrices A (M x N) and B (N x P) 
A = np.random.randint(0, 10, (M, N))
B = np.random.randint(0, 10, (N, P))

# A result matrix C (M x P) filled with zeros
C = np.zeros((M, P))

# Implement matrix multiplication without using numpy.dot
for i in range(M):
    for j in range(P):
        for k in range(N):
            C[i, j] += A[i, k] * B[k, j]

print(f'Matrix A is \n{A}')
print(f'Matrix B is \n{B}')
print(f'Result matrix C is \n{C}')


Matrix A is 
[[1 8 2 2]
 [9 5 7 9]
 [9 7 7 0]]
Matrix B is 
[[0 9]
 [7 7]
 [9 8]
 [1 0]]
Result matrix C is 
[[ 76.  81.]
 [107. 172.]
 [112. 186.]]


## Problem 1i (Bonus)

Show that for any matrix $\mathbf{A}$ the product $\mathbf{A}^T \mathbf{A}$ is symmetric.

## Problem 1j (Bonus)

Implement an algorithm that calculates $\mathbf{A}^T \mathbf{A}$ using the property of symmetry. Generate a huge matrix $\mathbf{A}$ and compare the running time between the implementation you did in 1h and the built-in matrix multiplication function.

In [31]:
import numpy as np
import time

M, N = 2,2
A = np.random.randint(0,2, (M,N))

# Calculate A^T A manually 
start_time = time.time()
AT_A_manual = np.dot(A.T, A)
manual_time = time.time() - start_time

# Calculate A^T A with built-in functions
start_time = time.time()
AT_A_builtin = A.T @ A
builtin_time = time.time() - start_time

print(f'A^T A calculated manually: \n{AT_A_manual}')
print(f'Time taken for manual calculation: {manual_time}')
print(f'A^T A calculated with built-in functions: \n{AT_A_builtin}')
print(f'Time taken for built-in calculation: {builtin_time}')


A^T A calculated manually: 
[[2 1]
 [1 1]]
Time taken for manual calculation: 0.00016808509826660156
A^T A calculated with built-in functions: 
[[2 1]
 [1 1]]
Time taken for built-in calculation: 0.0001537799835205078


## Problem 1k

Why do vectorized (or matrix-based) computations hold an advantage over traditional 'for' loops in Python?

Vektoriserte beregninger og matriseoperasjoner utført gjennom biblioteker som NumPy har flere fordeler:

- **Ytelse**: Bibliotekene er optimalisert for ytelse, med mange operasjoner implementert i lavnivåspråk som C og Fortran, som er raskere enn Python-løkker.
- **Parallelisering**: Disse operasjonene kan utnytte vektoriseringsegenskaper i moderne CPUer som SIMD (Single Instruction, Multiple Data) instruksjoner, og kan også benytte seg av multi-tråding og GPU akselerasjon der det er støttet.
- **Kodeklarhet**: Vektorisert kode er ofte mer lesbar og kortere, noe som gjør det lettere å vedlikeholde og feilsøke.

# Problem 2

In this task, we’ll use the basics of Git to clone an existing repo from GitHub and push some of it onto our own repository on GitHub. This task assumes Git has been installed. This can be done here: [Getting Started with Git](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git). 

This task might not present completely accurate information depending on how you’ve connected your computer to GitHub.

For more information on how to set up GitHub with SSH, have a look at the official documentation: [Connecting to GitHub with SSH](https://docs.github.com/en/authentication/connecting-to-github-with-ssh).


## Problem 2a
- First, make a folder called `GitTutorial` and navigate to this folder via a terminal.
- While inside this folder, use the command `git init` to initialize a local repository in that folder.
- Verify that a repository has been made by running `git status`.

-> skippet

## Problem 2b

- Next, we’ll clone an existing repository from GitHub to your local repository. The repository we’ll clone is this: [FYS-2021](https://github.com/Seilmast/FYS-2021).
- In the terminal, while still in the `GitTutorial` folder, use the `git clone` command and find the link on the GitHub page that references the online repository. This link is found by clicking the green "Code" button, and copying the HTTPS link. 
- This should now clone two files into your local repository.

In [34]:
# Command-line code here (no need to write anything in Python)

## Problem 2c

Now you should have two files locally on your computer: `UploadThis.txt` and `DoNotUploadThis.txt`.
   - We’ll first upload both these files to your remote repository. Follow these steps:
     1. Go to your GitHub account and make a new repository. When you’ve made one, there should be a link to set up the remote connection. If not, find the SSH link under the big green "Code" button.
     2. In your terminal, use the command `git remote <name> <link>` to link your remote and local repository. You can define the `<name>` yourself; it’ll be used to refer to the remote connection. The `<link>` should be the SSH link.
     3. Next, push `UploadThis.txt` to your repository. First, use `git add <file>` to prepare the files to be pushed. You may use `git add .` to add all files in the folder, but for now, just add the one file manually.
     4. Use `git commit -m <commit message>` to commit all the added files to be pushed. The `<commit message>` can be any string, but good form is to give a brief explanation of the changes made with the given commit.
     5. Lastly, use `git push <name>` (where `<name>` is the remote name you defined earlier) to push the commit to GitHub. Both files should now be on your repository.

In [35]:
# Command-line code here (no need to write anything in Python)

## Problem 2d

Create a `.gitignore` file and add `DoNotUploadThis.txt` to it, then push the changes to your repository.

In [36]:
# Command-line code here (no need to write anything in Python)

# Problem 3


Follow the notebook: https://github.com/udlbook/udlbook/blob/main/Notebooks/Chap01/1_1_BackgroundMathematics.ipynb. 

This is a complementary notebook for working with matrices and it prepares you for the next step when we see linear regression

# Problem 4

Follow the notebook: https://github.com/uitml/MLCourse2023/blob/main/code/NotebookTutorial.ipynb and try to understand each step. This is a simple notebook to refresh your Python skills about arrays and plotting.