# Exercise Set 1 - Vectorizing Code

This notebook contains the exercises from the PDF. Fill in your answers in the code cells provided.

# Problem 1

We ask the students to use Python as the programming language for this course. This is the standard language used for Machine Learning

## Problem 1a

Visit the following links to warm up with NumPy exercises:
- https://www.w3resource.com/python-exercises/numpy/basic/index.php
- https://www.w3resource.com/python-exercises/numpy/index-array.php
- https://www.w3resource.com/python-exercises/numpy/linear-algebra/index.php
- https://www.w3resource.com/python-exercises/numpy/python-numpy-stat.php

This course assumes you have a fair knowledge of how numerical programming, (i.e. working with vectors and matrices programatically), works. In the following exercises, we will look at writing efficient, vectorised code. Assume that we have vectors:
- $\mathbf{a} \in \mathbb{R}^n$ with elements $\mathbf{a} = [a_1, \dots, a_n]^T$
- $\mathbf{b} \in \mathbb{R}^n$ with elements $\mathbf{b} = [b_1, \dots, b_n]^T$

Further assume we have a matrix $\mathbf{X} \in \mathbb{R}^{M \times N}$

$$
\mathbf{X} = \begin{bmatrix}
x_{11} & x_{12} & \dots & x_{1N} \\
\vdots & \vdots & \ddots & \vdots \\
x_{M1} & x_{M2} & \dots & x_{MN}
\end{bmatrix}
$$

The result vector is $\mathbf{y}$ which takes its dimensionality based on the problem.

In all problems, you should assume that the dimensions of the vectors and matrices involved are such that the matrix multiplications (and inner products) are valid. Note that e.g. $\mathbf{y} += k$ is the same as $\mathbf{y} = \mathbf{y} + k$.

## Problem 1b

Write the following sum as a mathematical vector operation:

$$ y = \sum_{i=1}^{n} a_i b_i $$

The sum of the dot product of two vectors (a and b) can be written in vectorform as $$ y = a^Tb $$

Where: 
- $a^T$ is the transpose of vector a 
- $b$ is the vector with elements $b_1,b_2,…,b_nb_1​,b_2​,…,b$
- $y$ is the scalar result of the dot product 


In [16]:
# Can use Numpy to solve this problem 
import numpy as np

# Assuming a and b are numpy arrays 
a = np.array([1, 2, 3])                # a = np.array([a1, a2, ...., an])
b = np.array([4, 5, 6])                # b = np.array([b1, b2, ...., bn])

# Calculate the dot product of a and b
dot_product = np.dot(a, b)             # can also use sum(a*b)
print(f'The dot product of a and b is: {dot_product}')

The dot product of a and b is: 32


## Problem 1c

Write this **for** loop as a mathematical vector operation and as vectorised code. 

```
for i=1,. . .,n:
    y+=a_i * b_i
```

Mathematical vector operation:

$$ y = \mathbf{a}^T \mathbf{b} $$

In [131]:
import numpy as np
n = 3

# Generate random arrays a and b of size n from 0 to 10
a = np.random.randint(0, 10, n)
b = np.random.randint(0, 10, n)

# The dot product of a and b 
y = np.dot(a, b)

print(f'The vector a is {a}')
print(f'The vector b is {b}')
print(f'The dot product of a and b is {y}')

The vector a is [6 1 6]
The vector b is [1 9 7]
The dot product of a and b is 57


## Problem 1d

Write this **for** loop as a mathematical vector operation and vectorised code (assume N = n)
```
for i=1,. . .,M:
    for k=1,. . .,n:
        y_i += x_{ik} * a_k
```

In [132]:
import numpy as np
m = 2       # num rows in matrix
n = 2       # size of vectors and num columns in matrix       

# Generate random arrays a and b of size n from 0 to 10
x = np.random.randint(0, 10, (m, n))
a = np.random.randint(0, 10, n)

# The vector matrix product of x and a 
y = np.dot(x, a)

print (f'The matrix x is \n{x}')
print (f'The vector a is {a}')
print (f'The matrix vector product of x and a is {y}')

The matrix x is 
[[5 6]
 [7 0]]
The vector a is [7 2]
The matrix vector product of x and a is [47 49]


## Problem 1e

Vectorise the following algorithm (answer with code). This shouldn’t be done with traditional matrix multiplications alone
```
for i=1,. . .,M:
    for k=1,. . .,n:
        y += x_{ik} * a_k
```

In [145]:
import numpy as np
m = 2       # num rows in matrix
n = 2       # size of vectors and num columns in matrix       

# Generate random arrays a and b of size n from 0 to 10
x = np.random.randint(0, 10, (m, n))
a = np.random.randint(0, 10, n)

# The vector matrix product of x and a 
y = np.sum(x * a)

print (f'The matrix x is \n{x}')
print (f'The vector a is {a}')
print (f'The matrix vector product of x and a is {y}')

The matrix x is 
[[5 6]
 [2 4]]
The vector a is [6 5]
The matrix vector product of x and a is 92


## Problem 1f

Let $\mathbf{Z} \in \mathbb{R}^{P \times M}$ and $z_{ij} \in \mathbf{Z}$ be the entry in row $i$ and column $j$.

Vectorize the following algorithm:

```
for j=1,. . .,N:
    for i=1,. . .,P:
        for k=1,. . .,M:
            y_{ij} += z_{ik} * x_{kj}
```

Hint: Consider how to express the sum as a matrix multiplication.

In [176]:
import numpy as np
m = 2       # num collums in Z and rows in X
p = 2       # num rows in Z and rows in the result of y 
n = 2       # num columns in X and columns in the result of Z

# Generate random arrays a and b of size n from 0 to 10
z = np.random.randint(0, 10, (p, m))
x = np.random.randint(0, 10, (m, n))

# The vector matrix product of x and a 
y = np.dot(z, x)

print (f'The matrix x is \n {x}')
print (f'The  matrix z is \n {z}')
print (f'The matrix vector product of x and a is \n {y}')

The matrix x is 
 [[0 9]
 [8 7]]
The  matrix z is 
 [[9 5]
 [4 7]]
The matrix vector product of x and a is 
 [[ 40 116]
 [ 56  85]]


## Problem 1g

**NB: This part problem has different notation!**

Suppose you have a dataset with \(N\) samples and \(n\) features:

$$
\mathbf{x}_1, \dots, \mathbf{x}_N, \mathbf{x}_i = [x_{i1}, \dots, x_{in}] \in \mathbb{R}^n
$$

Similarly, you have parameter vectors \(\mathbf{w}_1, \dots, \mathbf{w}_P, \mathbf{w} \in \mathbb{R}^n\) and \(\mathbf{a} \in \mathbb{R}^P\).

Implement an algorithm, for every single sample \(\mathbf{x}_j = [x_{j1}, \dots, x_{jn}]\) in the dataset, that calculates:

$$
v_i = \sum_{k=1}^{n} w_{ik} x_{jk}
$$

$$
y_j = \sum_{i=1}^{P} v_i a_i
$$

Vectorize these expressions. You want to end up with a vector $(\mathbf{y} \in \mathbb{R}^N)$.


In [177]:
# Your code here

## Problem 1h (Bonus)

Implement an algorithm that does matrix multiplication (without using built-in matrix multiplication functions).

In [178]:
# Your code here

## Problem 1i (Bonus)

Show that for any matrix $\mathbf{A}$ the product $\mathbf{A}^T \mathbf{A}$ is symmetric.

In [179]:
# Your code here

## Problem 1j (Bonus)

Implement an algorithm that calculates $\mathbf{A}^T \mathbf{A}$ using the property of symmetry. Generate a huge matrix $\mathbf{A}$ and compare the running time between the implementation you did in 1h and the built-in matrix multiplication function.

In [180]:
# Your code here

## Problem 1k

Why do vectorized (or matrix-based) computations hold an advantage over traditional 'for' loops in Python?

In [181]:
# Your answer here

# Problem 2

In this task, we’ll use the basics of Git to clone an existing repo from GitHub and push some of it onto our own repository on GitHub. This task assumes Git has been installed. This can be done here: [Getting Started with Git](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git). 

This task might not present completely accurate information depending on how you’ve connected your computer to GitHub.

For more information on how to set up GitHub with SSH, have a look at the official documentation: [Connecting to GitHub with SSH](https://docs.github.com/en/authentication/connecting-to-github-with-ssh).


## Problem 2a
- First, make a folder called `GitTutorial` and navigate to this folder via a terminal.
- While inside this folder, use the command `git init` to initialize a local repository in that folder.
- Verify that a repository has been made by running `git status`.

In [182]:
# Command-line code here (no need to write anything in Python)

## Problem 2b

- Next, we’ll clone an existing repository from GitHub to your local repository. The repository we’ll clone is this: [FYS-2021](https://github.com/Seilmast/FYS-2021).
- In the terminal, while still in the `GitTutorial` folder, use the `git clone` command and find the link on the GitHub page that references the online repository. This link is found by clicking the green "Code" button, and copying the HTTPS link. 
- This should now clone two files into your local repository.

In [183]:
# Command-line code here (no need to write anything in Python)

## Problem 2c

Now you should have two files locally on your computer: `UploadThis.txt` and `DoNotUploadThis.txt`.
   - We’ll first upload both these files to your remote repository. Follow these steps:
     1. Go to your GitHub account and make a new repository. When you’ve made one, there should be a link to set up the remote connection. If not, find the SSH link under the big green "Code" button.
     2. In your terminal, use the command `git remote <name> <link>` to link your remote and local repository. You can define the `<name>` yourself; it’ll be used to refer to the remote connection. The `<link>` should be the SSH link.
     3. Next, push `UploadThis.txt` to your repository. First, use `git add <file>` to prepare the files to be pushed. You may use `git add .` to add all files in the folder, but for now, just add the one file manually.
     4. Use `git commit -m <commit message>` to commit all the added files to be pushed. The `<commit message>` can be any string, but good form is to give a brief explanation of the changes made with the given commit.
     5. Lastly, use `git push <name>` (where `<name>` is the remote name you defined earlier) to push the commit to GitHub. Both files should now be on your repository.

In [184]:
# Command-line code here (no need to write anything in Python)

## Problem 2d

Create a `.gitignore` file and add `DoNotUploadThis.txt` to it, then push the changes to your repository.

In [185]:
# Command-line code here (no need to write anything in Python)

# Problem 3


Follow the notebook: https://github.com/udlbook/udlbook/blob/main/Notebooks/Chap01/1_1_BackgroundMathematics.ipynb. 

This is a complementary notebook for working with matrices and it prepares you for the next step when we see linear regression

# Problem 4

Follow the notebook: https://github.com/uitml/MLCourse2023/blob/main/code/NotebookTutorial.ipynb and try to understand each step. This is a simple notebook to refresh your Python skills about arrays and plotting.